#===========================================================================
# allowed DPIs
#===========================================================================
dpis: [75, 150, 200, 300]

#===========================================================================
# the allowed scales
#===========================================================================
scales:
  - 160
  - 280
  - 560
  - 1150
  - 2000
  - 4500
  - 9000
  - 18000
  - 25000
  - 70000
  - 50000
  - 70000
  - 80000
  - 100000
  - 250000
  - 450000
  - 500000
  - 850000
  - 1000000
  - 1250000
  - 2000000
  - 3000000
  - 4000000
  - 5000000

#===========================================================================
# the list of allowed hosts
#===========================================================================
hosts:
  - !localMatch
    dummy: true
  - !ipMatch
    ip: www.camptocamp.org
  - !dnsMatch
    host: demo.opengeo.org
    port: 80
  - !dnsMatch
    host: terraservice.net
    port: 80
  - !dnsMatch
    host: sigma.openplans.org
  - !dnsMatch
    host: demo.mapfish.org
  - !dnsMatch
    host: a.tile.openstreetmap.org
  - !dnsMatch
    host: b.tile.openstreetmap.org
  - !dnsMatch
    host: c.tile.openstreetmap.org

layouts:
  Legal:
    mainPage:
      pageSize: LEGAL
      items:
        - !map
          spacingAfter: 30
          width: 440
          height: 483
  #===========================================================================
  A4 portrait:
  #===========================================================================
    metaData:
#      title: '${mapTitle}'
      author: 'MapFish print module'
      subject: 'Simple layout'
      keywords: 'map,print'
      creator: 'MapFish'

    mainPage:
      pageSize: A4
      rotation: true
#      header:
#        height: 50
#        items:
#          - !text
#            font: Helvetica
#            fontSize: 30
#            align: right
#            text: '${layout}'
      items:
        - !text
          text: '${mapTitle}'
          fontSize: 30
          spacingAfter: 30
        - !map
          spacingAfter: 30
          width: 500
          height: 600
        - !columns
          # columns can have an absolute position. In that case, they need the 3 following fields:
          absoluteX: 450
          absoluteY: 150
          width: 100
          items:
            - !scalebar
              type: bar
              maxSize: 100
              barBgColor: white
              fontSize: 8
              align: right
        - !text
          text: '${comment}'
          spacingAfter: 30
        - !attributes
          source: data
          spacingAfter: 30
          columnDefs:
            id:
              columnWeight: 2
              header: !text
                text: ID
                backgroundColor: #A0A0A0
              cell: !text
                text: '${id}'
            name:
              columnWeight: 5
              header: !text
                text: Name
                backgroundColor: #A0A0A0
              cell: !columns
                config:
                  cells:
                    - backgroundColor: '${nameBackgroundColor}'
                      borderWidth: 1
                      borderColor: '${nameBorderColor}'
                items:
                  - !text
                    text: '${name}'
        - !text
          font: Helvetica
          fontSize: 9
          align: right
          text: '1:${scale} ${now dd.MM.yyyy}'

      footer: &commonFooter
        height: 30
        items:
          - !columns
            config:
              cells:
                - paddingBottom: 5   
            items:
              - !text
                align: right
                text: 'Page ${pageNum}'
              - !image
                align: center
                maxWidth: 100
                maxHeight: 30
                spacingAfter: 200
                url: 'http://geoserver.org/img/geoserver-logo.png'
